api_platform:
  title: 'UGO API'
  version: '1.0.0'
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
  defaults:
    pagination_client_enabled: true
    pagination_client_items_per_page: true
    pagination_items_per_page: 10
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  keep_legacy_inflector: false
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header
  collection:
    pagination:
      enabled: true
  patch_formats:
    json: ['application/merge-patch+json']
  http_cache:
    invalidation:
      enabled: false
