framework:
  secret: '%env(APP_SECRET)%'
  handle_all_throwables: true
  http_method_override: false
  php_errors:
    log: true
  router:
    utf8: true
  serializer:
    enabled: true
  property_access:
    enabled: true
  validation:
    enabled: true

when@test:
  framework:
    test: true
